### ISSUE TITLE
Doctrine Demo does not work

### ISSUE THREAD

**Issue by jifeon** [eslint/doctrine#105]
Hi, thanks for great lib!

Looks like something wrong with Demo, `doctrine.js` does not found. Apparently, you have moved file inside `lib` folder and forget to change the link on demo page.

http://constellation.github.io/doctrine/demo/index.html

**Comment by tmcw** [comment]
@jifeon the new demo is located at http://eslint.org/doctrine/demo/ and it looks to be working properly from my system. Try out the new URL?

**Comment by jifeon** [comment]
Thx, it works now!
