### ISSUE TITLE
2D Array Syntax Not Supported

### ISSUE THREAD

**Issue by sunjay** [eslint/doctrine#108]
```
> doctrine.parse("/**@param {Number[]} test */", {unwrap: true, strict: true, sloppy: true})
{ description: '',
  tags: 
   [ { title: 'param',
       description: null,
       type: [Object],
       name: 'test' } ] }
> doctrine.parse("/**@param {Number[][]} test */", {unwrap: true, strict: true, sloppy: true})
DoctrineError: not reach to EOF
```

The latest jsdoc parses the `Number[][]` syntax. Please add support here.

Thank you

**Comment by niedzielski** [comment]
I think I'm seeing a similar issue:

Breaks:
```js
/** @return {!string[]} */
```

Works:
```js
/** @return {!Array.<string>} */
```

I believe this nullity syntax is supported per http://usejsdoc.org/tags-type.html

**Comment by grant** [comment]
This is my workaround:
```js
/**
 * @param {(string[])[]} values A 2d array of values to update.
 **/
```

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
