### ISSUE TITLE
exposed parsed representation of namepaths

### ISSUE THREAD

**Issue by jfirebaugh** [eslint/doctrine#109]
Doctrine has [namepath parsing](https://github.com/Constellation/doctrine/blob/da4635ec2e9cbb4b593b2bd49584defc5843abd8/lib/doctrine.js#L435-L447) but it appears to be for validation only: the value of the `name` tag is still a plain string.

Downstream consumers like [documentationjs](https://github.com/documentationjs/documentation) often want to work with a parsed representation, e.g. to normalize something like `@event Class#event` to `@name event, @kind event, @memberof Class`.

Could the parsed representation of namepaths be exposed similar to how the parsed representation of types is exposed. For example, `@event Class#event` could result in:

```
    "tags": [
        {
            "title": "event",
            "name": "Class#event",
            "path": {
              "type": "MemberPath",
              "parent": "Class",
              "member": "event",
              "scope": "instance"
            }
        }
    ]
```

I haven't investigated the taxonomy of namepaths too deeply (and I don't believe there is a formal specification), so `"MemberPath"` might not be the right `"type"`, but hopefully you get the gist.

**Comment by dignifiedquire** [comment]
I need this in documentation.js so I would like to work on this. Are there any pointers or ideas that were discussed about this I should know about?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
