### ISSUE TITLE
decomposition of doctrine.js

### ISSUE THREAD

**Issue by lbod** [eslint/doctrine#11]
Currently it's 1700 lines

I'm looking to possibly reuse this to generate docs for another OS library, however the size of doctrine.js is rather large.
Can it not be broken down, modularised etc to private functions?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
