### ISSUE TITLE
Allow invalid characters in @name

### ISSUE THREAD

**Issue by nknapp** [eslint/doctrine#114]
I'm trying to use doctrine to parse comments that look like jsdoc, but are actually in files of other languages, [like this handlebars-partial](https://github.com/nknapp/bootprint-swagger/blob/feature/thought/handlebars/partials/base/body.hbs)

``` hbs
{{!--
  Some description
  @name someName
  @param {string} a parameter
--}}
```

I chose doctrine, because it supports handling the comment-body and does not expect the surrounding `/**`,`*/` delimitiers. But now, I have the problem, that the partial-names in my module contain slashes which is perfectly valid for Handlebars-partials, but invalid for JavaScript identifiers.

I was wondering, if [the `scanIdentifier`-function](https://github.com/Constellation/doctrine/blob/master/lib/doctrine.js#L280) could just check for non-whitespace characters instead of performing a rigid check for valid JavaScript identifiers. I don't see much harm coming from that, since it would just mean that more names would be allowed. This wouldn't happen in a JavaScript-file, but it also wouldn't hurt if it did.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
