### ISSUE TITLE
Is it possible to support types or any additional parsing options for custom annotation types

### ISSUE THREAD

**Issue by Madd0g** [eslint/doctrine#115]
I couldn't find suitable tags in the closure compiler docs, so I used custom ones, which I'm reading with doctrine.

Unfortunately, it seems like only when I use tags like `@param` I get type parsing, in my custom tags all the contents of the comment goes into the description property. Is there a way to allow custom tags to have additional features or parsing rules?

Thanks

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
