### ISSUE TITLE
Replacing a collection with another does not remove replaced collection

### ISSUE THREAD

**Issue by guilhermeblanco** [eslint/doctrine#118]
I have a specific situation highlighted like this:

```
+-----+            +-----+
|  A  |--hasMany-->|  B  |
+-----+            +-----+
```

However, whenever I'm replacing the collection of B entities with a new collection, the old (replaced) collection entities are never removed.
I even configured `orphanRemoval=true`, but it seems there is no effect. 

Any hints on getting this working?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
