### ISSUE TITLE
Suggestions for a code analyzer to pair this with?

### ISSUE THREAD

**Issue by heff** [eslint/doctrine#12]
I'm looking to generate docs that are informed by both the comment tags and the code. Any suggestions on where to start?

**Comment by tmcw** [comment]
Cool, good discussion here!

I also maintain [a list of documentation generators](https://github.com/documentationjs/documentation/wiki/See-also), and would point to esdoc, typedoc, and documentation.js as major entrants in the 'inference assisted documentation' space. 

Closing this issue to keep Issues focused on actionable tasks, but feel free to continue discussing!
