### ISSUE TITLE
Make a unified representation of doc blocks

### ISSUE THREAD

**Issue by jonathanKingston** [eslint/doctrine#122]
As an extension to ESTree or a completely separate format it would be nice if doctrine could speak in a unified format which YUI and JSDoc could understand and share for a similar use-case to ESTree.

The problem of beginning to parse both I think suffers from being able to speak about the same statements in a unified manner.

As there is still fairly good support for YUI doc I think it would be worth having this however it could be harder to expand to other formats.

**Comment by nzakas** [comment]
Does YUIDoc and JSDoc already shared a common format?

**Comment by jonathanKingston** [comment]
It is pretty universal, the structure is slightly different in that YUI has primary and secondary tags where as JSDoc is a little more informal. I'm not actually sure if there are any syntax differences other than different tags and conventions.

**Comment by nzakas** [comment]
Since you're passionate about this, I'd like to suggest you do some research and post back here examples of Doctrine, YUIDoc, and JSDoc output for the same docblocks.

**Comment by jonathanKingston** [comment]
It's probably fair to say I'm not going to get time to complete this unless it became a requirement of my next job (Which it looks like it won't be).

I'm going to close this as it looks like I'm the only one pushing for this however I'm available to walk through this if anyone has an interest in it.
