### ISSUE TITLE
@param arg1 [optional] is not handled correctly

### ISSUE THREAD

**Issue by nicjansma** [eslint/doctrine#129]
Using ESLint v1.4.3, I am seeing a crash in `valid-jsdoc.js`.  Please see this issue for details:
https://github.com/eslint/eslint/issues/3893 and PR https://github.com/eslint/eslint/pull/3894

This is because `tag.name` is not set from doctrine.  Here's the sample JSDoc that reproduces this issue:

```
* @param arg1 [optional] description
```

A change from @gyandeeps fixes something similar: https://github.com/eslint/doctrine/pull/126, but only addresses consecutive `[]`s, not something like `[optional]`.

**Comment by gyandeeps** [comment]
I just tested it. Works fine.
I tested it with eslint also. Works fine.

**Comment by nicjansma** [comment]
Apologies, I was using `gruntify-eslint`, which I had was locked to `"^0.1.1"`, keeping ESLint at an older version.

The latest `gruntify-eslint` and `eslint` don't crash here anymore.

**Comment by gyandeeps** [comment]
Awesome.
