### ISSUE TITLE
Allow omission of type in returns tag

### ISSUE THREAD

**Issue by tmcw** [eslint/doctrine#136]
Currently doctrine permits syntax like

```js
/**
 * @param foo - this is a param
 */
```

But not the same for return values

```js
/**
 * @returns foo - this is a return value
 */
```

Having both tags with optional type annotations would be great since the type annotations can often inferred by Flow/TS.

**Comment by nzakas** [comment]
Does JSDoc support typeless returns currently?

**Comment by tmcw** [comment]
Yep, I can confirm that JSDoc supports typeless returns

<img width="501" alt="2015-11-07 at 12 21 pm" src="https://cloud.githubusercontent.com/assets/32314/11016277/20f7b5ee-854a-11e5-96de-a74a23cecd63.png">
