### ISSUE TITLE
Parser fails on optional params.

### ISSUE THREAD

**Issue by jdalton** [eslint/doctrine#149]
doctrine ignores the param tag and any other tag on it if it encounters the `[props]` bit.

```
     * @param {string} [props] The property names to pick
```

~~Similarly it fails to parse this too~~
~~` * @param {string[]} props The property names to pick`~~

**Comment by jdalton** [comment]
It fails on this too
```
     * @param {string[]} props The property names to pick
```

**Comment by nzakas** [comment]
I'm sorry, there's not enough information here. Before I can look into this, I need to know:

1. What version are you using?
1. What is the complete code block you're trying to parse?
1. What is the expected output?
1. What did you actually get?

**Comment by jdalton** [comment]
Hmm I'm actually trying on the [demo](http://eslint.org/doctrine/demo/) page but notice it's a really old version, 0.0.4-dev, and the current is 1.1.0.

The input was in the demo text.
![example](https://cloud.githubusercontent.com/assets/4303/12959924/8330b6c8-cfed-11e5-828c-7c711770b457.gif)

**Comment by nzakas** [comment]
Yeah, the demo is really old. It's not tied into the release process, so I think it was easily forgotten. I'm pretty sure this works in the latest version.

**Comment by jdalton** [comment]
Is updating the demo smth I can PR?

**Comment by jdalton** [comment]
Ok confirmed the second case, `@param {string[]} props text`, works in v1.1.0,
but the first case, `@param {string} [props] text` doesn't.

**Comment by nzakas** [comment]
What do you mean when you say it doesn't work? Is there an error? What is happening?

**Comment by jdalton** [comment]
I posted the gif above which shows what's happening.
When you provide an comment the optional `[` `]`'s it doesn't parse the option and ignores any param below it. Using `sloppy` mode will grab the entire line but not parse the `param`.

**Comment by jdalton** [comment]
Btw big props on creating a parser. I'm relying on regexes for this kind of thing and just try to wish away the regex in my mind.

**Comment by nzakas** [comment]
I'll take a look.

Your thanks should go to @Constellation, he wrote the parser. I'm just trying to help maintain it. :)

**Comment by demoneaux** [comment]
I don’t think that’s a bug, you have to enable the `sloppy` option to enable parsing of optional arguments using the `[opt]` format. See the [`parse()` docs for more info](https://github.com/eslint/doctrine/blob/master/README.md#parse).

**Comment by jdalton** [comment]
@demoneaux 
> I don’t think that’s a bug, you have to enable the sloppy option to enable parsing of optional arguments using the [opt] format. See the parse() docs for more info.

Read me comment just above
> . Using sloppy mode will grab the entire line but not parse the param.

**Comment by jdalton** [comment]
Actually I take it back. I tried it again without leading '*' in the test case and it does appear to parse the param. I needed to pass the `unwrap` as `true` option.
