### ISSUE TITLE
parens problems

### ISSUE THREAD

**Issue by jdalton** [eslint/doctrine#150]
This works

```
     * @param {...(string|number)} props The property names to pick
```

This doesn't

```
     * @param {(...(string|number))} props The property names to pick
```

JSDoc parser recommends the second example (the one that doesn't work with doctrine)
to work around [an issue in their parser](https://github.com/hegemonic/catharsis/issues/47).

Related to #149.

**Comment by nzakas** [comment]
When you say "it doesn't work", what does that mean? Are you saying there's an error thrown? Something else?

**Comment by jdalton** [comment]
Like #149 this is from the [demo](http://eslint.org/doctrine/demo/) page.
![demo](https://cloud.githubusercontent.com/assets/4303/12960145/88866afe-cfee-11e5-9cf9-0c33ebdd9b2f.gif)

**Comment by jdalton** [comment]
This still has issues in v1.1.0.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
