### ISSUE TITLE
opening block tags

### ISSUE THREAD

**Issue by automaticgiant** [eslint/doctrine#153]
I'm not sure if there is a JSDoc spec I missed about this, but Doctrine fails to correctly parse JSDoc blocks with opening block tags. Examples:

``` javascript
/**
 * @function
 * description, not name
 * @returns {boolean} false
 */

{ description: '/**', tags: [] }
```

``` javascript
/**
 * @function
 * asdf
 * @returns {boolean} false
 */

{ description: '/**',
  tags: 
   [ { title: 'function', description: null, name: 'asdf' },
     { title: 'returns', description: 'false\n/', type: [Object] } ] }
```

``` javascript
/**
 * @function
 * @name asdf
 * asdf does stuff
 * @returns {boolean} false
 */

{ description: '/**',
  tags: [ { title: 'function', description: null, name: null } ] }
```

**Comment by nzakas** [comment]
What you're seeing is a parsing error. Doctrine tries not to throw errors when it runs into a problem, so what you're seeing is the recovery mechanism. I'm not familiar with the intricacies of function `@function` is supposed to work and which of these are valid or invalid behavior. Can you explain some more or point to any references you might have?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
