### ISSUE TITLE
Indicate description prefix

### ISSUE THREAD

**Issue by jgeurts** [eslint/doctrine#155]
Right now hyphens/dashes are removed from parameter descriptions. It would be nice to have that description prefix added to the AST, to be available for analysis. Eg. If I wanted to write a lint rule to enforce descriptions to start with dash space.

**Comment by nzakas** [comment]
In what situation would you need this information?

**Comment by jgeurts** [comment]
In the case where a lint rule would like to enforce a dash between parameter name and description. Right now, the dash & space are removed from the description.

**Comment by nzakas** [comment]
Are you referring to ESLint or something else?

Keep in mind, what you're asking for is concrete syntax information inside an abstract syntax tree, which is always a bit dicey.

**Comment by jgeurts** [comment]
Yep, referring to eslint.

**Comment by nzakas** [comment]
How would you propose such information be included?

**Comment by jgeurts** [comment]
Honestly, I'm not sure... 

Maybe the description could include the `- ` portion that is currently removed. Or a `descriptionPrefix` property could be added to the AST with the portion of the description that gets stripped out.

**Comment by nzakas** [comment]
Modifying the description would be unexpected and a breaking change, so I don't think we can do that. 

`descriptionPrefix` with a string doesn't really give you the information you want, because you would have no spacing information. 

I'll leave this open for a bit to see if anyone has other ideas.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
