### ISSUE TITLE
@alias tag with multiple values.

### ISSUE THREAD

**Issue by jdalton** [eslint/doctrine#159]
**What version are you using?**
^1.2.0

**What JSDoc comment were you trying to parse?**
```js
/**
@alias foo, bar, baz
*/
```
**What Doctrine options were you using (sloppy, unwrap, etc.)?**
```js
{
  'lineNumbers': true,
  'recoverable': true,
  'sloppy': true,
  'unwrap': true
}
```

**What happened? Include output if possible.**
```js
// the tag
{
description: null,
errors: ["Unknown content ', bar, baz'"],
name: "foo",
title: "alias"
}
```
**What did you expect to happen?**

I expected it to parse it as something similar to `@memberOf` and return a tag like:
```js
{
"title": "alias",
"description": "foo, bar, baz"
}
```

**Comment by nzakas** [comment]
I can't find any documentation indicating that `@alias` should support multiple names. Do you have a reference?

**Comment by jdalton** [comment]
I don't but it seems like there could be, and often are, multiple aliases for a method.

**Comment by nzakas** [comment]
As best I can tell, this is invalid JSDoc syntax so the parser is behaving correctly. Closing for now, but if you find a reference saying that JSDoc does support this syntax, please paste back here and I will reopen.

**Comment by jdalton** [comment]
Inquiring over at https://github.com/jsdoc3/jsdoc/issues/1195.
