### ISSUE TITLE
Support quotes in @function external:"myexternal".myFunction

### ISSUE THREAD

**Issue by cyChop** [eslint/doctrine#166]
### What version are you using?

1.2.2 (ESLint 3.0.1)
### What JSDoc comment were you trying to parse?

``` javascript
    /**
     * Creates a {@link BeveragesView} in the selected elements.
     *
     * @function external:"jQuery.fn".beverages
     * @param {Object} options the options for the beverages view
     */
```
### What Doctrine options were you using (sloppy, unwrap, etc.)?

Don't know, used by ESLint for validating [the `valid-jsdoc` rule](http://eslint.org/docs/rules/valid-jsdoc).
### What happened? Include output if possible.

ESLint fails to validate the `valid-jsdoc` rule. Output is:

```
X:\some\path\beverages.js
  21:5  error  JSDoc syntax error  valid-jsdoc
```

Removing the quotes seems to fix the problem of parsing, but the documented function then disappears from the generated documentation.
### What did you expect to happen?

The code was supposed to be valid. It is largely inspired (almost directly copied) from [JSDoc's own documentation and examples](http://usejsdoc.org/tags-external.html).

**Comment by tmcw** [comment]
My bug PR describes the same problem as this: https://github.com/eslint/doctrine/pull/165

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
