### ISSUE TITLE
Doctrine fails to parse @param documentation for optional parameters with default value

### ISSUE THREAD

**Issue by cyChop** [eslint/doctrine#168]
### What version are you using?

Doctrine 1.2.2 (ESLint 3.0.1)

### What JSDoc comment were you trying to parse?

```javascript
/**
 * Adds an order for the specified beverage.
 *
 * If an order already exists for this beverage, its quantity will be incremented by one.
 *
 * @param {Beverage} beverage the beverage an order is being passed for
 * @quantity {number} [quantity=1] the quantity being ordered
 * @public
 */
order: function (beverage, quantity) {
```

### What Doctrine options were you using (sloppy, unwrap, etc.)?

Used in ESLint

### What happened? Include output if possible.

ESLint failed to enforce the `valid-jsdoc` rule.

```
D:\somewhere\beverages-js\src\js\model\order\order-summary.js
  40:13  error  Missing JSDoc for parameter 'quantity'  valid-jsdoc

✖ 1 problem (1 error, 0 warnings)
```

### What did you expect to happen?

The parameter should be recognized.

See JSDoc's documentation: http://usejsdoc.org/tags-type.html (line: "Optional parameter").

**Comment by nzakas** [comment]
It looks like you have a syntax error: `@quantityis`  not a valid tag. Try replacing it with `@param`

**Comment by cyChop** [comment]
OK, I'm ashamed of having let that pass through. No problem once my code is correct indeed. Thanks and sorry again!
