### ISSUE TITLE
Doctrine doesnt support function type with argument

### ISSUE THREAD

**Issue by xuesu** [eslint/doctrine#169]
**What version are you using?**
1.2.2

**What JSDoc comment were you trying to parse?**
        /**
         * Create key-value caches of limited size
         * @returns {Function(string, Object)} Returns the Object data after storing it on itself with
         *	property name the (space-suffixed) string and (if the cache is larger than Expr.cacheLength)
         *	deleting the oldest entry
         */

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
unwrap:true

**What happened? Include output if possible.**
It cant parse the tags until I change it into:
        /**
         * Create key-value caches of limited size
         * @returns {Function} Returns the Object data after storing it on itself with
         *	property name the (space-suffixed) string and (if the cache is larger than Expr.cacheLength)
         *	deleting the oldest entry
         */
**What did you expect to happen?**
It can parse a tag whose content is function(string,Object), or at least a tag whose type is function

**Comment by nzakas** [comment]
As far as I can tell, that's not valid JSDoc syntax. See http://usejsdoc.org/tags-type.html

**Comment by xuesu** [comment]
thank you!
