### ISSUE TITLE
More informative error messages

### ISSUE THREAD

**Issue by Pomax** [eslint/doctrine#175]
Stemming from https://github.com/eslint/eslint/issues/7194#issuecomment-249449717, the current doctrine code does not expose errors in a way that a larger eslint run can tap into. For instance, using eslint on code with JSDocs like this will trigger a "JSDoc syntax error":

```
/**
 * Some description
 * @param {string or boolean} param1 can be either a string or boolean representing blah blah
 * @returns {undefined}
 */
function dosomething(param1) {
  if (param1) {
    ...
  }
}
```

But "JSDoc syntax error" doesn't tell us what is actually wrong: spaces are not allowed in `@param`/`@return(s)` definitions, and so doctrine fails, but it can take a very long time for a user to find this error without a helpful error message that guide them. In this case, something like the following error, which eslint can tap into, would be extremely useful:

```
JSDoc syntax error: spaces found in @param definition for SomeVarName. To specify multiple types, use the pipe character, '|'.
```

**Comment by kaicataldo** [comment]
The issue is actually not that doctrine is swallowing errors/not exposing them to ESLint and more that the parser is unable to parse that syntax and throws an error. It might be possible to improve the error messaging in this specific case, which I think is what this issue should be specifically about.

**Comment by nzakas** [comment]
I'm not sure there's anything that can be done here. Parsers just throw on syntax errors, they rarely tell you *why* the syntax is incorrect. I'm not sure we want to start down the rabbit hole of testing for specific error cases to give better error messages.

**Comment by platinumazure** [comment]
@nzakas Even acorn/espree will say things like "Unexpected token ':'"-- I don't think it's unreasonable for the community to ask for doctrine to get to that point. "JSDoc syntax error" is a useless error message.

**Comment by Pomax** [comment]
There's a difference between the parser telling you that "there is and error", "the is this error: ...", and "there is this error: ..., and this is my guess at how to fix it".

Asking a parser to do all three is certainly a massive undertaking (and sometimes literally impossible), but it would be entirely reasonable to expect a parser to be able to do the first two. Just having it generate "there is an error" is technically not information: there *might* be an error, or there might be a bug in doctrine. Without knowing what doctrine thinks is actually wrong, there is no way to distinguish between those two cases.

So it feels like at the very least doctrine should be able to report "JSDoc syntax error: unexpected token ' ' in @param type on input.js:177". This tells users that the parser thinks there's an error, tells them what the parser thinks the error is, and tells them where the parser thinks the error can be found, and thus where it can be fixed, as well as enabling the user to tell whether or not they are at fault (99.99% of the cases that will be true) or whether they ran unto a doctrine bug that can be reported with exactly the code that triggers it and a good string label that lets you find out where in the doctrine parser code this bug occurs.

**Comment by nzakas** [comment]
Full disclosure: I didn't write Doctrine, I just agreed to help keep it alive. I don't actually understand the code well enough to know how to do what you're requesting. And unfortunately, I'm quite ill and don't have the energy to dig in and figure it out. 

If you (or anyone), would like to submit a pull request for this, I'll happily review it.

**Comment by Pomax** [comment]
arr, all the best to you. not sure when and if I'll have time, but hopefully someone who does and has the same requirements will find this issue and resolve it for us =)

**Comment by mnpenner** [comment]
Doctrine is crapping out on this doc block:

```js
/**
 * Perform an asynchronous HTTP (Ajax) request.
 * 
 * @param {String|Object} url A string containing the URL to which the request is sent, or the settings object.
 * @param {Object=} settings A set of key/value pairs that configure the Ajax request. All settings are optional.
 * @param {Object=} settings.accepts A set of key/value pairs that map a given \`dataType\` to its MIME type, which gets sent in the Accept request header. This header tells the server what kind of response it will accept in return.
 * @param {Boolean=} settings.async By default, all requests are sent asynchronously (i.e. this is set to true by default). If you need synchronous requests, set this option to false.
 * @param {Function=} settings.beforeSend A pre-request callback function that can be used to modify the jqXHR.
 * @param {Boolean=} settings.cache If set to false, it will force requested pages not to be cached by the browser.
 * @param {Function=} settings.complete A function to be called when the request finishes (after success and error callbacks are executed).
 * @param {Object=} settings.contents An object of string/regular-expression pairs that determine how jQuery will parse the response, given its content type.
 * @param {Boolean|String=} settings.contentType When sending data to the server, use this content type. Default is "application/x-www-form-urlencoded; charset=UTF-8", which is fine for most cases.
 * @param {Object=} settings.context This object will be the context of all Ajax-related callbacks.
 * @param {Object=} settings.converters An object containing dataType-to-dataType converters. Each converter's value is a function that returns the transformed value of the response.
 * @param {Boolean=} settings.crossDomain If you wish to force a crossDomain request (such as JSONP) on the same domain, set the value of crossDomain to true. This allows, for example, server-side redirection to another domain.
 * @param {Object|String|Array=} settings.data  Data to be sent to the server. It is converted to a query string, if not already a string. It's appended to the url for GET-requests.
 * @param {Function=} settings.dataFilter A function to be used to handle the raw response data of XMLHttpRequest. This is a pre-filtering function to sanitize the response. You should return the sanitized data. The function accepts two arguments: The raw data returned from the server and the 'dataType' parameter.
 * @param {String=json} settings.dataType The type of data that you're expecting back from the server. If none is specified, jQuery will try to infer it based on the MIME type of the response.
 * @param {Function=} settings.error A function to be called if the request fails.
 * @param {Boolean=true} settings.global Whether to trigger global Ajax event handlers for this request.
 * @param {Object=} settings.headers An object of additional header key/value pairs to send along with requests using the XMLHttpRequest transport.
 * @param {Boolean=false} settings.ifModified Allow the request to be successful only if the response has changed since the last request. This is done by checking the Last-Modified header.
 * @param {Boolean=} settings.isLocal Allow the current environment to be recognized as "local," (e.g. the filesystem), even if jQuery does not recognize it as such by default.
 * @param {String|Boolean=} settings.jsonp Override the callback function name in a JSONP request.
 * @param {String|Function=} settings.jsonpCallback Specify the callback function name for a JSONP request.
 * @param {String=} settings.mimeType A mime type to override the XHR mime type.
 * @param {String=} settings.password A password to be used with XMLHttpRequest in response to an HTTP access authentication request.
 * @param {Boolean=true} settings.processData By default, data passed in to the data option as an object (technically, anything other than a string) will be processed and transformed into a query string, fitting to the default content-type "application/x-www-form-urlencoded". If you want to send a DOMDocument, or other non-processed data, set this option to false.
 * @param {String=} settings.scriptCharset Only applies when the "script" transport is used (e.g., cross-domain requests with "jsonp" or "script" dataType and "GET" type). Sets the charset attribute on the script tag used in the request. Used when the character set on the local page is not the same as the one on the remote script.
 * @param {Object=} settings.statusCode An object of numeric HTTP codes and functions to be called when the response has the corresponding code.
 * @param {Function=} settings.success A function to be called if the request succeeds.
 * @param {Number=} settings.timeout Set a timeout (in milliseconds) for the request.
 * @param {Boolean=} settings.traditional Set this to true if you wish to use the traditional style of param serialization.
 * @param {String=GET} settings.type An alias for method. A string containing the URL to which the request is sent.
 * @param {String|Object=} settings.url A string containing the URL to which the request is sent, or an object to be sent to \`wxu.link()\`.
 * @param {String=} settings.username A username to be used with XMLHttpRequest in response to an HTTP access authentication request.
 * @param {Function=} settings.xhr Callback for creating the XMLHttpRequest object.
 * @param {Object=} settings.xhrFields An object of fieldName-fieldValue pairs to set on the native XHR object.
 * @returns {Promise.<Object>} Resolved when XHR request completes with 2xx status code, rejects otherwise
 * @see https://api.jquery.com/jquery.ajax/
 */
```

And I can't for the life of me figure out where it's bailing. I've tried removing some of the `@param`s one y one, but it doesn't appear to be any particular one that's causing the error. 

If I set `recoverable: true` then Doctrine makes it to the end. So it's silently dying somewhere, for some reason, but it's not giving me any hints.

Even a line number would go a long way to help me diagnose this problem. Surely the parser at least knows it's character position when it died?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
