### ISSUE TITLE
License and copyright issues

### ISSUE THREAD

**Issue by SnarkBoojum** [eslint/doctrine#176]
Hi,

I'm trying to package doctrine in Debian, but I'm hitting the following issues:
1. README.md says something about closure-compiler and there's even a LICENSE.closure-compiler, file but I haven't seen anything about it in the code ;
2. README.md also mentions some functions are derived from esprima and there's a LICENSE.esprima  file, but I don't know which ;
3. Concerning the licenses, both esprima and doctrine are under BSD-2-clause so things are clearly ok, but for the closure-compiler, it's an Apache-2.0 : I don't think it's ok to relicense in this direction.

Could you clarify the matter?

Thanks,

Snark on #debian-js

**Comment by nzakas** [comment]
I'm sorry, I don't know much about any of this history. @Constellation can you comment?

**Comment by SnarkBoojum** [comment]
I'm still waiting for feedback on the matter : Debian is serious (some say picky) about licenses, so I'm quite stuck.

**Comment by nzakas** [comment]
Sorry, unfortunately there's nothing else I can do here. @Constellation created the package originally, and if he's not responding, I don't know how else to help.

**Comment by SnarkBoojum** [comment]
Perhaps you have a personal email on which we could try to reach @Constellation -- in case he doesn't check github on a regular basis ?

**Comment by Constellation** [comment]
Oops, sorry. I'm checking... bugs.webkit.org regularly.

> README.md says something about closure-compiler and there's even a LICENSE.closure-compiler, file but I haven't seen anything about it in the code ;

Some of the type annotation extensions are derived from closure complier's one. Doctrine's type annotation is extended from the JSDoc's one at that time.

> README.md also mentions some functions are derived from esprima and there's a LICENSE.esprima file, but I don't know which ;

Several utility functions like https://github.com/eslint/doctrine/blob/master/lib/typed.js#L103-L116

> Concerning the licenses, both esprima and doctrine are under BSD-2-clause so things are clearly ok, but for the closure-compiler, it's an Apache-2.0 : I don't think it's ok to relicense in this direction.

Hm, is it better relisencing doctrine under apache-2.0?

**Comment by nzakas** [comment]
I'll have to ask the JS Foundation about re-licensing.

**Comment by nzakas** [comment]
I spoke with the JS Foundation and they confirmed we can re-license as Apache 2. I'll put together a pull request for that.

**Comment by SnarkBoojum** [comment]
When will you do a release with updated copyright&license ?

Thanks.

**Comment by nzakas** [comment]
Just published doctrine@2.0.0 with the updated license (I consider re-licensing to be a breaking change, but there are no functional differences in the package).
