### ISSUE TITLE
@requires not being parsed as expected

### ISSUE THREAD

**Issue by PetarMax** [eslint/doctrine#177]
I'm having problems (see below) with the parsing of the `@requires` tag. Is it reserved/special in some way? 

Thanks,
Petar

**What version are you using?**
1.5.0

**What JSDoc comment were you trying to parse?**
`
/** @requires this and that */
`

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
`unwrap : true`

**What happened? Include output if possible.**
`
{
    "description": "",
    "tags": []
}
`

**What did you expect to happen?**
`
{
    "description": "",
    "tags": [
        {
            "title": "requires",
            "description": "this and that"
        }
    ]
}
`

**Comment by mdasberg** [comment]
any update?

**Comment by platinumazure** [comment]
@mdasberg I don't believe anyone has had time to investigate. If you have time to investigate and send a PR, we would be hugely grateful.

@eslint/doctrine-team Pinging in case anyone can provide a more accurate update.

**Comment by tmcw** [comment]
Sure, trying this out in the [demo](https://eslint.org/doctrine/demo/) reveals the cause:

![image](https://user-images.githubusercontent.com/32314/30356205-78c44b64-97ec-11e7-8c90-00a576c7516d.png)

The syntax of `@requires` allows [a namepath](http://usejsdoc.org/tags-requires.html) after the tag, but not a description, so the input is invalid.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
