### ISSUE TITLE
Invalid name for @this

### ISSUE THREAD

**Issue by joscha** [eslint/doctrine#179]
**What version are you using?**

1.5.0

**What JSDoc comment were you trying to parse?**

```js
doctrine.parse('/** @this {!Node}', {
  strict: true,
  unwrap: true,
  sloppy: true
});
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**

all of them

**What happened? Include output if possible.**
an error gets thrown:
```js
{ [DoctrineError: Invalid name for this] name: 'DoctrineError', message: 'Invalid name for this' }
```

**What did you expect to happen?**

to get an AST

**Comment by nzakas** [comment]
`@this` must be a namepath, so what you have is invalid syntax. See http://usejsdoc.org/tags-this.html

**Comment by joscha** [comment]
O, I missed that completely - thanks @nzakas

**Comment by joscha** [comment]
Just for reference - the Closure Compiler `@this` annotation is incompatible with the JSDoc one - see https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler
