### ISSUE TITLE
Support type intersections

### ISSUE THREAD

**Issue by joelday** [eslint/doctrine#183]
Same syntax as type unions, but with `&` as the delimiter instead of `|`. Thanks!

**Comment by nzakas** [comment]
I'm sorry, this isn't enough for us to evaluate your request. Please update this issue with examples and links to relevant JSDoc docs showing what you're requesting. Thanks!

**Comment by joelday** [comment]
Hi! Here are a few recent examples of intersection types as a JavaScript language feature:

https://flowtype.org/docs/union-intersection-types.html
https://www.typescriptlang.org/docs/handbook/advanced-types.html

Could do this currently, but it'll wind up being a NameExpression. I assume that won't work with whitespace, though?

**Comment by joelday** [comment]
@nzakas Went ahead and submitted a PR for this. Thanks again!

**Comment by not-an-aardvark** [comment]
@joelday Thanks! I'm not familiar enough with the `doctrine` codebase to review the PR, so I'll leave that to someone else. However, I do have a question -- does [JSDoc](http://usejsdoc.org/) itself specify that intersection types should be supported? While TypeScript and Flow do have support for intersection types with particular semantics, to my knowledge `doctrine` typically only supports features if they're actually part of the JSDoc spec.

**Comment by joelday** [comment]
@not-an-aardvark Thanks! Doesn't look like JSDoc supports it. (jsdoc3/jsdoc#1285) I'll be working on that end of it now.

**Comment by nzakas** [comment]
Unfortunately, we can't include features that aren't supported by JSDoc itself. Doing so creates a lot of confusion and we would be forced to support every dialect that is tangentially related to JSDoc, which is untenable. 

If JSDoc decides to support it, please comment back here so we can re-evaluate.

**Comment by joelday** [comment]
@nzakas I haven't heard anything from JSDoc yet. I'd like to close this for the time being so that it doesn't clutter up your open issues list.

**Comment by nzakas** [comment]
Sounds good. Feel free to reopen later.

**Comment by not-an-aardvark** [comment]
Looks like the consensus was to close this issue, so I'll do that.
