### ISSUE TITLE
What's the reason for the dot in stringifing TypeExpression (Array.<string>)?

### ISSUE THREAD

**Issue by davidfirst** [eslint/doctrine#185]
Doctrine stringifies a TypeExpression with a dot after the type. 
For example, parsing `@param {string[]}` and passing the type tag to` doctrine.type.stringify()`, yields `Array.<string>`. 
I would expect it to be: `Array<string>` because that's normally how a type of other types is represented.  
In the JS world, that's how Flow and TypeScript handle it, also in JSDoc docs, it's mentioned in the same way (http://usejsdoc.org/tags-interface.html).

I would like to open a PR, but not sure if there was a reason to add this dot. 

(for a reference, the implementation of the dot is here: https://github.com/eslint/doctrine/blob/master/lib/typed.js#L1242).

**Comment by Constellation** [comment]
IIRC, this `Array.<String>` was the old form of the type annotation of the closure compiler.
This `doctrine` project originally starts to accept type annotations for the closure compiler.

Now, I think there is no reason to dump this old form in doctrine.

**Comment by nzakas** [comment]
I just pinged @constellation to see if he has any background for this.

**Comment by davidfirst** [comment]
Interesting. Thanks for the info. 

Just FYI, I have found that the dot is optional in the closure compiler:
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System (look at the "Type Application" section).

I would say, the reason to change it is for readability. The end user doesn't understand why the dot is there, as this is not common. However, it's up to you guys. I'm closing the ticket.
