### ISSUE TITLE
Add support for @property without type

### ISSUE THREAD

**Issue by tibdex** [eslint/doctrine#186]
**What version are you using?**
_2.0.0_

**What JSDoc comment were you trying to parse?**
```javascript
/**
 * @typedef {Object} Point
 * @property x The x coordinate of the point.
 * @property y The y coordinate of the point.
 */
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
_none_

**What happened? Include output if possible.**
The propery descriptions are lost:

```json
{
    "description": "/**",
    "tags": [
        {
            "title": "typedef",
            "description": null,
            "type": {
                "type": "NameExpression",
                "name": "Object"
            },
            "name": "Point"
        }
    ]
}
```

**What did you expect to happen?**
I'm using [documentation.js](https://github.com/documentationjs/documentation) with `flow` annotations so my source code is actually:
```javascript
/**
 * @typedef {Object} Point
 * @property x The x coordinate of the point.
 * @property y The y coordinate of the point.
 */
type Point = {
  x: number,
  y: number
};
```
I would have liked `doctrine` to keep the property descriptions in the output so that `documentation.js` could merge them with the types infered from the `flow` annotations.

I checked and `JSDoc` _3.4.3_ already supports typeless properties:
![jsdoc](https://cloud.githubusercontent.com/assets/6574550/23303981/a78c9098-fa97-11e6-87e6-e8f40f835770.png)

A similar development has already been done for typeless `@param` #16. If `doctrine` also adds support for typeless `@property`, it would solve the second example of:      https://github.com/documentationjs/documentation/issues/226.

I can see, that there is currently a [test enforcing that `@property` must have a type](https://github.com/eslint/doctrine/blob/master/test/parse.js#L859). Is it by design ? If I were to submit a PR to change this behaviour, would you be willing to merge it ?

Thanks :)

**Comment by jbe456** [comment]
Hi,

A pull request has been made on this topic: https://github.com/eslint/doctrine/pull/187

Would it be possible to have a look? @nzakas @Constellation 

Thanks!

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
