### ISSUE TITLE
Mechanism for 'escaping' @ symbol when part of an example (i.e. Decorators)

### ISSUE THREAD

**Issue by Ghnuberath** [eslint/doctrine#188]
**What version are you using?**
Using 2.0.0 through https://github.com/documentationjs/documentation

**What JSDoc comment were you trying to parse?**
```javascript
/**
 * @example
 * const Module = require('ravel').Module;
 * @inject('path')
 * class MyModule extends Module {
 *   constructor (path) {
 *     super();
 *     this.path = path;
 *   }
 * }
 */
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
sloppy: true

**What happened? Include output if possible.**
I believe that Doctrine is treating my decorator as a JSDoc tag, and thus breaking the remainder of my code out of the example. From the Doctrine demo:

```js
{
    "description": "",
    "tags": [
        {
            "title": "example",
            "description": "const Module = require('ravel').Module;"
        },
        {
            "title": "inject",
            "description": "('path')\nclass MyModule extends Module {\nconstructor (path) {\nsuper();\nthis.path = path;\n}\n}"
        }
    ]
}
```

**What did you expect to happen?**
It would be awesome if there was an elegant way to escape the `@` symbol so that Doctrine would treat it as part of the example. See https://github.com/documentationjs/documentation/issues/698 for more details.

**Comment by nzakas** [comment]
Have you tried escaping with a slash?

**Comment by Ghnuberath** [comment]
Escaping with a slash is definitely what I would have assumed would work, and I've tried both forward and back slashes. While this does prevent the code sample from being broken into two parts, doctrine doesn't remove the slash, producing an incorrect code example.

I'd expect this:
```js
/**
 * @example
 * const Module = require('ravel').Module;
 * \@inject('path')
 * class MyModule extends Module {
 *   constructor (path) {
 *     super();
 *     this.path = path;
 *   }
 * }
 */
```

To result in this:
```js
{
    "description": "/**",
    "tags": [
        {
            "title": "example",
            "description": "const Module = require('ravel').Module;\n@inject('path')\nclass MyModule extends Module {\n  constructor (path) {\n    super();\n    this.path = path;\n  }\n}\n/"
        }
    ]
}
```

But instead, I get this:
```js
{
    "description": "/**",
    "tags": [
        {
            "title": "example",
            "description": "const Module = require('ravel').Module;\n\\@inject('path')\nclass MyModule extends Module {\n  constructor (path) {\n    super();\n    this.path = path;\n  }\n}\n/"
        }
    ]
}
```

Forward slashes work similarly and are also not removed. This means that the example passed through to `documentationjs` shows incorrect syntax for decorator usage (since it includes the slash).

**Comment by jdom** [comment]
Is there an update to this? I'm trying to do the same thing

**Comment by Ghnuberath** [comment]
I ended up faking it. In my docs, I use `&#64;mydecorator` to represent `@mydecorator`  in all my examples, then post-process in gulp: https://github.com/raveljs/ravel/blob/master/gulpfile.js#L34

Nothing about the solution is elegant, but I couldn't wait so this is what I ended up with.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
