### ISSUE TITLE
Option for allowing multiple tags per line.

### ISSUE THREAD

**Issue by justinfagnani** [eslint/doctrine#191]
We're using doctrine to parse some codebases annotated for Closure compiler and have multiple tags per line, since Closure allows it. I know this isn't strictly supported in JSDoc, but it'd be great to have the option to parse them as separate tags.

cc https://github.com/Polymer/polymer-analyzer/issues/475

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
