### ISSUE TITLE
fails to read @name tags with slashes

### ISSUE THREAD

**Issue by andykais** [eslint/doctrine#197]
Hi, trying to make the names of jsdoc entries routes for use in documentationjs

**What version are you using?**
- present in 2.0.0
- and the fork in documentationjs `doctrine-temporary-fork": "2.0.0-alpha-allowarrayindex"`

**What JSDoc comment were you trying to parse?**
```
/**
 * @name /route
*/
```
will yield `null/route`, I expected `/route/`

```
/**
 * @name /
*/
```
will error, I expected `/`
```
TypeError: Cannot read property 'match' of undefined
      at scanIdentifier (lib/doctrine.js:23:537)
      at parseName (lib/doctrine.js:24:3257)
      at TagParser._parseNamePath (lib/doctrine.js:34:213)
      at TagParser.parseNamePath (lib/doctrine.js:34:905)
      at TagParser.parse (lib/doctrine.js:82:214)
      at parseTag (lib/doctrine.js:85:96)
      at Object.parse (lib/doctrine.js:90:1097)
      at Context.<anonymous> (test/parse.js:394:28)
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
`unwrap: true`

this is referenced in documentationjs [#454](https://github.com/documentationjs/documentation/issues/454),
and PR #165 

I tested this in the source code, found [this line](https://github.com/eslint/doctrine/blob/master/lib/doctrine.js#L270) to be the problem with `@names` starting with slash, and stack trace is mentioned above in for names with only `/`

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
