### ISSUE TITLE
Support for relative type references

### ISSUE THREAD

**Issue by tschaub** [eslint/doctrine#205]
**What version are you using?**

https://eslint.org/doctrine/demo/ as of today (looks like it was updated with https://github.com/eslint/doctrine/commit/77f3536649346d04939cdc017cd76088332b6240)

**What JSDoc comment were you trying to parse?**

```
@param {./path/to/Module.NamedExport} arg A type that comes from another module.
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**

`recoverable`

**What happened? Include output if possible.**

```json
{
    "description": "",
    "tags": [
        {
            "title": "param",
            "description": "A type that comes from another module.",
            "type": null,
            "errors": [
                "unexpected token"
            ],
            "name": "arg"
        }
    ]
}
```

**What did you expect to happen?**

```json
    "description": "",
    "tags": [
        {
            "title": "param",
            "description": "A type that comes from another module.",
            "type": {
                "type": "NameExpression",
                "name": "./path/to/Module.NamedExport"
            },
            "name": "arg"
        }
    ]
}
```

The Closure Compiler allows the [use of types with relative paths](https://github.com/google/closure-compiler/wiki/JS-Modules#type-references) (to avoid unused imports).  For example, if `Module.js` includes this code:

```js
/**
 * Some exported type.
 * @typedef {{foo: boolean}}
 */
export let NamedExport;
```

Then a consuming module can use that type without an explicit (unused) import.  E.g.:

```js
/**
 * Some function that uses a type from another module.
 * @param {./path/to/Module.NamedExport} arg The typed argument.
 */
function run(arg) {
  // ...
}
```

Would this project accept a pull request that made it so that `./path/to/Module.NamedExport` was parsed as a name expression (or some new type)?

**Comment by platinumazure** [comment]
Hi @tschaub, thanks for the issue!

Does the JSDoc standard itself allow for this, or is this a Closure Compiler extension?

**Comment by tschaub** [comment]
Good question @platinumazure.  I don't know that JSDoc annotations have been formally specified - maybe I'm wrong about this.

Relative type references are not currently supported by [JSDoc 3](https://github.com/jsdoc3/jsdoc), and they are not documented at http://usejsdoc.org/.  There is a pull request for [Catharsis](https://github.com/hegemonic/catharsis) (JSDoc's parser) to add support for them (see hegemonic/catharsis#52).

So, I think it is fair to say that relative type references are supported by the Closure Compiler, but will not likely gain widespread use without support in ESLint and JSDoc.  I don't know of an alternative solution for documenting and type checking ES modules that works for both JSDoc and the Closure Compiler.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
