### ISSUE TITLE
@example warp the decorator does NOT work

### ISSUE THREAD

**Issue by imcuttle** [eslint/doctrine#207]
**What version are you using?**
v2.1.0

**What JSDoc comment were you trying to parse?**
```js
/**
 * @example
 *  class Model extends Root {
 *      @urlSync
 *      @observable sync = 'abc'
 *  }
 * @public
 */
function urlSync () {...}
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
```js
{ unwrap: true }
```

**What happened? Include output if possible.**
- output
```text
[ { title: 'example', description: 'class Model extends Root {' } ]
```

**What did you expect to happen?**
- output
```text
[ { title: 'example', description: 'class Model extends Root { \n  @urlSync .... }' } ]
```

**Comment by not-an-aardvark** [comment]
Thanks for creating an issue. Does [JSDoc](https://github.com/jsdoc3/jsdoc) support this syntax?

Keep in mind that decorators are not part of ES6, and are still a [stage 2 proposal](https://github.com/tc39/proposal-decorators). At the earliest, they will end up being part of ES2019 ("ES10").

**Comment by jaydenseric** [comment]
Duplicates https://github.com/eslint/doctrine/issues/188?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
