### ISSUE TITLE
The type is in 'name' when there is no name

### ISSUE THREAD

**Issue by bary12** [eslint/doctrine#209]
**What version are you using?**
2.1.0

**What JSDoc comment were you trying to parse?**
```
/**
 * @param {string}
 */

```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
```
{
      range: true,
      unwrap: true,
      lineNumbers: true,
      recoverable: true
}

```
**What happened? Include output if possible.**

```
{
  "description": "",
  "tags": [
    {
      "title": "param",
      "description": null,
      "lineNumber": 1,
      "range": [
        6,
        21
      ],
      "type": null,
      "name": "string"
    }
  ]
}
```

**What did you expect to happen?**
Expected `type` to be `"string"` and `name` to be `null`

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
