### ISSUE TITLE
"Strict" parsing mode?

### ISSUE THREAD

**Issue by nzakas** [eslint/doctrine#21]
For ESLint, I really want to know when there's a syntax error in a JSDoc comment (JSDoc will usually error out). Right now, Doctrine silently ignores most errors and continues on to parse the rest. Is it possible to have a mode that throws errors when they occur rather than continuing on? Some examples I'd like to be able to catch:

``` js
// double @
/**
 * Description
 * @@param {string} name Param description
 */

// missing closing curly brace
/**
 * Description
 * @param {string name Param description
 * @param {int} foo Bar
 */
```

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
