### ISSUE TITLE
Support `@access package`

### ISSUE THREAD

**Issue by jaydenseric** [eslint/doctrine#214]
See:

- http://usejsdoc.org/tags-access.html
- http://usejsdoc.org/tags-package.html

**What version are you using?**

v2.1.0

**What JSDoc comment were you trying to parse?**

```
Description.
@access package
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**

- recoverable

**What happened? Include output if possible.**

```

{
    "description": "Description.",
    "tags": [
        {
            "title": "access",
            "description": null,
            "access": "package",
            "errors": [
                "Invalid access name 'package'"
            ]
        }
    ]
}
```

Without the recoverable option:

```
{
    "description": "Description.",
    "tags": []
}
```

**What did you expect to happen?**

```
{
    "description": "Description.",
    "tags": [
        {
            "title": "access",
            "description": null,
            "access": "package"
        }
    ]
}
```

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
