### ISSUE TITLE
Support for TypeScript import types

### ISSUE THREAD

**Issue by tschaub** [eslint/doctrine#215]
**What version are you using?**

https://eslint.org/doctrine/demo/ as of today.

**What JSDoc comment were you trying to parse?**

`@param {import("path/to/module").Foo} arg The argument.`

**What Doctrine options were you using (sloppy, unwrap, etc.)?**

`recoverable`

**What happened? Include output if possible.**

```json
{
    "description": "",
    "tags": [
        {
            "title": "param",
            "description": "The argument.",
            "type": null,
            "errors": [
                "not reach to EOF"
            ],
            "name": "arg"
        }
    ]
}
```

**What did you expect to happen?**

```
{
    "description": "",
    "tags": [
        {
            "title": "param",
            "description": "The argument.",
            "type": {
                "type": "NameExpression",
                "name": "import(\"path/to/module\").Foo"
            },
            "name": "arg"
        }
    ]
}
```

TypeScript allows for types to be imported inline.  See examples here: https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript
```
// We can also import declarations from other files using 
// 'import' types:

/**
 * @param p { import("./a").Pet }
 */
function walk(p) {
    console.log(`Walking ${p.name}...`);
}
```

Unfortunately, ESLint's `valid-jsdoc` rule does not allow these same types.  It would be great if the linter rule allowed these import types.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
