### ISSUE TITLE
doctrine not parsing @Param with default value

### ISSUE THREAD

**Issue by shivshankar3578** [eslint/doctrine#217]
**What version are you using?**
https://eslint.org/doctrine/demo/

**What JSDoc comment were you trying to parse?**
`@param {{p1:string [foo], p2:Number}} obj `

**What Doctrine options were you using (sloppy, unwrap, etc.)?**
sloppy=true

**What happened? Include output if possible.**

**What did you expect to happen?**
I need to define object structure with default value

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
