### ISSUE TITLE
Support inline tags

### ISSUE THREAD

**Issue by nzakas** [eslint/doctrine#23]
JSDoc has several inline tags that can appear as part of a description. For example: http://usejsdoc.org/tags-link.html

It would be good to represent this in some way in Doctrine, especially if they appear to be a syntax error, such as:

``` js
/**
 * Hello {@link world!
 */
```

**Comment by tmcw** [comment]
Happy to take a look at this - I'll see if there's a way to at least lex this input.

**Comment by tmcw** [comment]
@Constellation what do you think of the approach in https://github.com/documentationjs/jsdoc-inline-lex ? I want to keep this step agnostic to how the documentation is formatted eventually, so lexing ideally makes it possible to output markdown / html / etc

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
