### ISSUE TITLE
Support JSDoc 3 optional param style

### ISSUE THREAD

**Issue by nzakas** [eslint/doctrine#25]
JSDoc 3 supports this syntax for specifying optional params:

``` js
/* 
 * @param {Object} [location] An object containing the error line and column
 */
```

Right now, Doctrine throws a syntax error when it encounters this pattern. More info: http://usejsdoc.org/tags-param.html

**Comment by jdalton** [comment]
Sloppy mode doesn't actually add support for this. See #149.
