### ISSUE TITLE
Rename sloppy to jsdoc3

### ISSUE THREAD

**Issue by Constellation** [eslint/doctrine#26]
Basically doctrine supports Closure compiler tags.
But jsdoc3 tags are useful, so we need to support it.

Currently jsdoc3 style optional param is supported when `sloppy` flag is on. This is not suitable name. We should rename `sloppy` to something like `jsdoc3`.

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
