### ISSUE TITLE
Support JSDoc 3 tags

### ISSUE THREAD

**Issue by Constellation** [eslint/doctrine#5]
http://usejsdoc.org/index.html#JSDoc3_Tag_Dictionary

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
