### ISSUE TITLE
Some multiline tags support please?

### ISSUE THREAD

**Issue by zxqfox** [eslint/doctrine#76]
Is there possibility to add multiline parsing of some tags? Or just param tag?

Test case:

``` js
var jsdoc = ['/**', 'Info', '@param {', '  {status: ?boolean},', '  {hint: ?boolean}', '} [condition] some info about ', 'condition param', '@param {boolean} yes'].join('\n * ')+'\n */';
console.log(jsdoc);
require('doctrine').parse(jsdoc, {unwrap:true});
```

And no tags ;-(

```
/**
 * Info
 * @param {
 *   {status: ?boolean},
 *   {hint: ?boolean}
 * } [condition] some info about
 * condition param
 * @param {boolean} yes
 */
{ description: 'Info', tags: [] }
```

Problem is here: mdevils/node-jscs#245

**Comment by danez** [comment]
For some tags (like example) it is working.

**Comment by nzakas** [comment]
@zxqfox can you give an example where you're seeing a problem?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
