### ISSUE TITLE
lineNumbers doesn't provided in throws

### ISSUE THREAD

**Issue by zxqfox** [eslint/doctrine#84]
``` js
doctrine.parse('@param ', {strict: true, lineNumbers: true})
```

throws

``` js
{ name: 'DoctrineError', message: 'Braces are not balanced' }
```

Can exceptions have location (at least line, but better column) of an error?

**Comment by kaicataldo** [comment]
Thanks for this issue. We have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. As a result, this repository and project will no longer be maintained.

Thanks for understanding and we apologize for any inconvenience.
