### ISSUE TITLE
Last tag always has \n in the description

### ISSUE THREAD

**Issue by Madd0g** [eslint/doctrine#87]
Hi,

the `unwrap: true` option fails to strip the last new line before `*/`, so an empty description on the last tag in the comment always becomes '/' (not sure why) and a non-empty description always has a newline at the end.

In my code, I have to do this to remove spaces/newlines from before the end of the comment, before passing the comment to doctrine.
     
     comment = comment.replace(/[\s\n]*\*\/[\s\n]*$/, '*/');

Thanks

**Comment by gyandeeps** [comment]
Related https://github.com/eslint/doctrine/issues/107

**Comment by gyandeeps** [comment]
@nzakas I think this can be closed too as was related to #107 and that is closed.

**Comment by nzakas** [comment]
@Madd0g what version are you using!

**Comment by Madd0g** [comment]
@nzakas - 0.6.4 was the last version I used.

**Comment by gyandeeps** [comment]
@Madd0g Can you please try 0.7.0?

**Comment by Madd0g** [comment]
@gyandeeps - sorry for the delayed reply - I upgraded to 0.7.0, I still see a `\n` in the end of the last tag.
